name: Build and Deploy
on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/build.yml'
      - 'VERSION'
jobs:
  build:
    name: Pipeline
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the source code
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./docker/production.dockerfile
          platforms: linux/amd64,linux/arm64
          tags: zavy86/wikidocs:latest
          push: true
